### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by 89z** [SGNight/Arm-NativeBridge#1]
Is it possible to use Houdini with Android Studio Virtual Device?

**Comment by SGNight** [comment]
yes it's possible.

**Comment by 89z** [comment]
how is it done?

**Comment by SGNight** [comment]
android studio in linux supports KVM virtualization with arm64 apps support, so you can use android apps on it without any lag like windows emulation.
it's not possible to add android x86 houdini files to android studio emulator because both are build differently, and windows android studio uses QEMU emulator which doesn't use intel houdini files so it's not that good.
